### ISSUE TITLE
Deposit contract's `depositTransaction` needs a `mint` parameter

### ISSUE THREAD

**Issue by norswap** [ethereum-optimism/optimistic-specs#104]
This will be needed in case we allow paying deposit fees in ETH, as [proposed here](https://github.com/ethereum-optimism/optimistic-specs/issues/78#issuecomment-999750666).

As that part of the proposal received no challenge, I think we can go ahead and introduce the extra parameter instead of setting the minting that `msg.value`. It's also a more general interface, which is good in case we need to upgrade to change things.

**Comment by norswap** [comment]
@maurelian Assigning you since you wrote the contract, feel free to re-assign to me if you have other things to do.

**Comment by maurelian** [comment]
I think the decision on the fee proposal is still pending.
