### ISSUE TITLE
L1 <> Driver <> L2 integration Go tests

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimistic-specs#121]
The driver functions are tested individually, but to ensure the contracts behave as expected, we should take compiled bytecode and test L1 deposit calls getting derived into L2 transactions. e2e also covers this, but having it in CI + no sync/API noise would be nice for testing.

TODO:
- [ ] Decide how to consume contract bytecode in Go tests.
- [ ] In-memory state db + chain db.
- [ ] Wrap with `core.GenerateChain` to add deposit transactions
- [ ] Some random deposits to the chain
- [ ] Run driver with block/receipts
- [ ] Apply produced L2 block to second in-memory chain
- [ ] Check if balances etc. updated as expected (assert invariants hold)

Questions
- Should we check-in contract artifacts? Or maybe just the byte-code to embed in testing state? Or do we run Go tests after `yarn build` anyway in CI? (creates a dependency between jobs though)
- In addition to randomness, any other deposit edge-cases we want to test?
- Shall we spec invariants for effects of L1 deposits to L2 chain? This makes testing easier

**Comment by trianglesphere** [comment]
I've been working on this. The setup I've gone with is shelling out to `l1geth` and `l2geth` and then running the rollup node from in golang.

Other options: Setup `l1geth` and `l2geth` to run from inside golang. I'll look into it, and the more I think about it, it's probably doable.

Consuming bytecode: Currently hardcoded, but other options are compiling and pulling in from the environment or trying to use `go generate`

Status

- [ ] Create genesis
- [ ] Initialize L1 & L2 Geth
- [ ] Run L1 & L2 Geth
- [ ] Run the rollup node
- [ ] Submit a deposit transaction
- [ ] Verify the balance change on L2

**Comment by maurelian** [comment]
Can we close this issue @trianglesphere?

**Comment by trianglesphere** [comment]
Fixed in https://github.com/ethereum-optimism/optimistic-specs/pull/154
