### ISSUE TITLE
Gas optimize DepositFeed

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/optimistic-specs#134]
We can gas-golf the unindexed data part of the deposit-log, to not use 6*32 bytes. (boolean, is unnecessary, data length is unneccessary because we only have a single dynamic length bytes, and data-offset is always 160). cc @maurelian

_Originally posted by @maurelian in https://github.com/ethereum-optimism/optimistic-specs/issues/128#issuecomment-1012521210_

**Comment by mslipper** [comment]
Tracked in ENG-2001.
