### ISSUE TITLE
Milestone epic: Output commitment

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimistic-specs#156]
A client mode running a rollup-node and execution engine, submitting state roots to a L2 Output Oracle contract.

- [ ] Review existing state-root contract
  - > We should be able to reuse much of the existing batch submitter and SDK code here, and will involve the code owners of those components.
    > The main diff between what we have now and v1.0 is we can remove the ‘batch’ state root submission, and just submit 1 root per n L1 blocks.
- Spec
  - [x] #168
    - See [issue 153](https://github.com/ethereum-optimism/optimistic-specs/issues/153), this can greatly help reduce withdrawal cost
  - [x] #194
  - [x] #169
- Contracts:
  - [x] #167
- Rollup node, root claimer extension (part of sequencer, but anyone must be able to do it technically):
  - [x] #170
    - Either extend rollup-node, or modify existing standalone code to do the new updated job
- Rollup node, challenger extension:
  - [x] #171

**Comment by maurelian** [comment]
Items to convert to issues:
- Proto can start on specing form of commitment
- John to begin working on contract once spec is ready
- Josh and or Connor to start on batch submitter impl

**Comment by protolambda** [comment]
Proposer is done, spec is there, output roots etc. can be constructed. Closing this
