### ISSUE TITLE
"L2 output commitment oracle" Contract spec

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/optimistic-specs#169]
A draft of the contract can be found in this [gist](https://gist.github.com/karlfloersch/02ce7938000680ce7820f39ba06bd9b1), and updated abi-bindings [here](https://github.com/cfromknecht/optimism/blob/bss-output-commitment/go/batch-submitter/bindings/sro/state_root_oracle.go).

**Comment by mslipper** [comment]
Tracked in ENG-1973.
