### ISSUE TITLE
Clearly define security properties

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/optimistic-specs#177]
So far we have specified what the protocol _should_ do, but we should also take the time to explicitly define what it _should not_ do or allow. 

This could take the form of a document or section entitled "security properties" which outlines the invariants we need to maintain. 

Creating this content has the benefits of:
- Guiding test code towards more "sad path" test cases. 
- Enabling auditors and verification engineers to better focus their efforts. 
- Helping us to write better, more defensive code and better understand what it means for the system to be secure. 

This [section](https://github.com/statechannels/SAFE-protocol/blob/279620e/doc/SAFE.md#security-claims) of the SAFE protocol spec by Magmo is a good example. I can dig up some others I've seen in my travels.

**Comment by mslipper** [comment]
Closing in favor of some more specific Linear tasks.
