### ISSUE TITLE
Specifiy the difference between a verifier and sequencer in `overview.md`

### ISSUE THREAD

**Issue by karlfloersch** [ethereum-optimism/optimistic-specs#18]
**Is your feature request related to a problem? Please describe.**
It's currently confusing that in https://github.com/ethereum-optimism/optimistic-specs/blob/main/overview.md#components there is no mention of how the sequencer software is different from the verifier. This should be clarified.

**Describe the solution you'd like**
Split out the diagram into multiple agents.

**Comment by norswap** [comment]
I'm closing this in the spirit of the repo reboot. I don't think we'll forget to do this. Feel free to reopen if you disagree and think this should stay as an open issue.
