### ISSUE TITLE
Daisy-chain RPC proxy - chain upgradeability idea

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimistic-specs#180]
Idea by @karlfloersch, storing it here for future upgrade discussion.

Problem: When squash-forking, we get rid  of old DB contents, old API types, etc. in geth. During the transition we may have both, but long-term no more than the latest version should be supported for minimal protocol complexity. Yet, some users like to access older data with the *same* RPC as the newer data.

Solution: Keep a node running (disconnected, frozen at last block before fork) and serve data with it. Wrap it with a RPC proxy, and "daisy-chain" the request: try latest node first, then try the previous, and then the one before, etc. This proxy can be super minimal/simple, since it only reads error codes and does not "speak" the protocol (i.e. no individual methods to re-route, just handle "not found" etc. errors). Now the RPC proxy can be called for results of any time in the protocol. And users that only need the latest data can access it through a regular non-proxy setup.

**Comment by mslipper** [comment]
Mark has a spec out for this, and is starting implementation. Closing since this is complete.

**Comment by norswap** [comment]
Is this going to land on the specs repo at some point? I think we should try to centralize the spec information in one location.
