### ISSUE TITLE
Update derivation with sequencer block construction from L1 batch data

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimistic-specs#185]

**Comment by norswap** [comment]
Something we discussed with @protolambda and @trianglesphere is that how compression should interact with block derivation.

The candidate solution we came up with is that L2 block derivation should take as an input the sequencing window (as before) but also the full header of the previous L2 block (previously, we only needed its number and hash).

We would write in L2 block headers the current compression ratio, and whenever deriving an epoch worth from L2 block from an L1 block, we would read the compression ratio from the previous L2 block's header, and use this ratio to:
1. verify the fees charged by the sequencer
2. update the compression ratio with the effective compression ratio for batches contained within the sequencing window

Some naming open questions:
- How do we call the first block of an epoch (the one that includes the deposit transaction). Proposal: the *epoch start L2 block*.
- There is a distinction between "submitted transactions for a single L2 block" and "a submission to the L1 batch contract containing transactions for one or more L2 blocks". Proto's current implementation assumes *one batch* = one block and that a single submission can submit multiple batches.
     - Do we want to keep this terminology and use the terms *a batch* and *a batch submission* or do we want other terms?
