### ISSUE TITLE
Harden Downloader w/ batching, concurrency limits and memoization

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimistic-specs#187]
PR #221 simplified the downloader to continue with sequencing work, but removed some features also. For production we should improve the downloader:
- Sanity limit on concurrency
- Improved retries and timeouts
- Implement memoization (that other code already assumes)
- Provide more optionality in what to download (we don't need receipts of all blocks right away, only for the start of a window)

**Comment by mslipper** [comment]
I think we can should this to use batched RPCs rather than multiple concurrent requests.
