### ISSUE TITLE
Transaction Receipt Parity

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimistic-specs#216]
**Is your feature request related to a problem? Please describe.**
In the existing system, the transaction receipt is serialized differently compared to L1 ethereum.
See the differences here: https://github.com/ethereum-optimism/optimism/blob/43f16dd06b7173a6b8a6703fec984df8b2ea91c2/l2geth/core/types/receipt.go#L70
This decision was made to enable Etherscan to easily display the L1 fee paid.
This data can be fetched assuming that the user has an archive node, since the L1 gas price (basefee)
is held in the L2 state. Placing the data in the transaction receipt no longer means that the user
needs an archive node to compute the total fee paid. This is a problem for any code that does receipt
serialization. Since the receipts are committed to in the block hash (block header contains the receipts
root), the shape of the receipt is part of consensus and developers will need custom code to serialize
the receipts.

**Describe the solution you'd like**
We should revert to using ethereum style receipts for 1.0 and write a helper function in the sdk that can
easily compute the L1 fee. Since the "deposit tx" will include the L1 basefee, it should be as simple
as fetching the block that the tx was included in, look at the deposit tx and then look at the size of the
tx to compute the L1 gas used and multiple the L1 basefee by the L1 gas used.

**Describe alternatives you've considered**
This is assuming that the fee model will be similar to how it is right now

**Comment by tynes** [comment]
The consensus serialization does not include the L1 fee data: https://github.com/ethereum-optimism/optimism/blob/43f16dd06b7173a6b8a6703fec984df8b2ea91c2/l2geth/core/types/receipt.go#L144

**Comment by norswap** [comment]
I think we do indeed want to do:

> ... and write a helper function in the sdk that can
easily compute the L1 fee. Since the "deposit tx" will include the L1 basefee, it should be as simple
as fetching the block that the tx was included in, look at the deposit tx and then look at the size of the
tx to compute the L1 gas used and multiple the L1 basefee by the L1 gas used.

Is there an issue tracking this somewhere?
