### ISSUE TITLE
chore: Update PayloadID type to upstream geth core.beacon.PayloadID

### ISSUE THREAD

**Issue by norswap** [ethereum-optimism/optimistic-specs#218]
See comment here: https://github.com/ethereum-optimism/optimistic-specs/pull/127#discussion_r786782654

The type is now merged in geth (it's here: https://github.com/ethereum/go-ethereum/blob/20356e57b119b4e70ce47665a71964434e15200d/core/beacon/types.go)

This involves:
- rebasing [our geth fork](https://github.com/ethereum-optimism/reference-optimistic-geth) on top of geth 1.10.16
- updataing the imports
- changing the types

**Comment by norswap** [comment]
@protolambda does that look good? Want to do it? I'll do if necessary, just let me know.

**Comment by protolambda** [comment]
There are other Engine API changes (mostly renames, and subtle effects to syncing) that we'll also need to adopt if we rebase our geth diff on the latest version. For now I would prioritize keeping open sequencing PRs + blobs EIP moving. I could do the rebase/integration of latest geth after that.

**Comment by protolambda** [comment]
Closing this, this was implemented upstream long ago here: https://github.com/ethereum/go-ethereum/pull/24236 and we use the type already.
