### ISSUE TITLE
Add Acknowledgements 

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/optimistic-specs#236]
We are not working in a vacuum; so much of our work draws on existing work by others and we can do better at crediting them.

We should create an ACKNOWLEDGEMENTS.md file in this repo to ack/cite them. This [tweet](https://twitter.com/aliatiia_/status/1501928474931572739) from @aliatiia is a good starting point.

**Comment by norswap** [comment]
The cartesi whitepaper: https://cartesi.io/cartesi_whitepaper.pdf

**Comment by ef3n9r98** [comment]
Hi @maurelian, I know some devs who'd be interested in working on this. Is there a budget for fixing this issue, and if so, how much? 

I'd put this issue up on [OpenQ](http://www.openq.dev/).

Thanks!

**Comment by Oceeapril** [comment]
Found it interesting but the new solution beats this🚀
