### ISSUE TITLE
Make the batch submitter stateless + other improvements

### ISSUE THREAD

**Issue by norswap** [ethereum-optimism/optimistic-specs#257]
We have currently merged a simplistic version of the batch submitter.

As [outlined here](https://github.com/ethereum-optimism/optimistic-specs/pull/248#issuecomment-1069368484), there are a few things to improve.

- Crucially, we want to determine the batches to submit from the L1 head and L2 unsafe head.
- Less urgently, but also quite desirable, make the submitter more robust, e.g. with some retry logic.

(I'm tentatively assigning this @cfromknecht, cc @mslipper)

**Comment by protolambda** [comment]
Working on this this week

**Comment by protolambda** [comment]
This issues is pretty outdated, I'm closing it. The batch-submitter has the minimum storage already: a history (json encoded) of L2 blockhashes (the last blockhash of each bundle of batches that was submitted). Storing less than that would cause inconsistent/lagging L1 data to cause sequencing problems (duplicates primarily). And it can already start without such history file if really needed.
