### ISSUE TITLE
Opnode should retry L1/L2 connection on startup

### ISSUE THREAD

**Issue by mslipper** [ethereum-optimism/optimistic-specs#259]
When the opnode starts, it tries to dial the L1 and L2 endpoints. When running in a `docker-compose` environment, however, the L1 and L2 endpoints will come up after the opnode will. To fix this, we should retry the L1/L2 connection on opnode startup.

**Comment by protolambda** [comment]
If a `rpc.Client` connection fails, it will return an error, but you still get client bindings back if it's http or ws I think, which will then keep retrying to connect on usage.

If it's an IPC connection though I think it will just error without returning any client that retries, and then we've to retry ourselves.

**Comment by mslipper** [comment]
Yeah, I saw that logic. I have a solution that should work for both.
