### ISSUE TITLE
Computing the L2 Deposit Tx Hash Client Side

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimistic-specs#348]
**Is your feature request related to a problem? Please describe.**
When a user sends a L1 -> L2 transaction, the user wants to know what the L2 transaction hash is so that they can know when the deposit goes through. Right now, the `DepositTx` has this schema:

```ts
interface DepositTxOpts {
  blockHeight: BigNumberish
  transactionIndex: BigNumberish
  from: string
  to: string | null
  mint: BigNumberish
  value: BigNumberish
  gas: BigNumberish
  data: string
}
```

This is problematic because the L2 blockheight and L2 transactionIndex are included in the transaction. This means that the user needs to brute force the L2 tx hash to know when it goes through on L2. See the hardhat task changes here: https://github.com/ethereum-optimism/optimistic-specs/pull/347/files for how this would look in the sdk

**Describe the solution you'd like**
I'd like to be able to compute the L2 tx hash locally just using the receipt of the L1 transaction. This could be accomplished by changing the struct of the `TxDeposit` to:

```ts
interface DepositTxOpts {
  sourceHash: string
  from: string
  to: string | null
  mint: BigNumberish
  value: BigNumberish
  gas: BigNumberish
  data: string
}
```
Where `sourceHash` is `keccack256(receipt.blockHash || receipt.txIndex || receipt.eventIndex)`.
The `sourceHash` is required to ensure that transaction hashes are unique on L2.
The event index is required because a single L1 transaction can create multiple L2 transactions by calling the deposit contract multiple times.

**Comment by tynes** [comment]
https://github.com/ethereum-optimism/reference-optimistic-geth/pull/9

**Comment by protolambda** [comment]
See #351
