### ISSUE TITLE
What about "*fault proof*"?On 28  March 12th and 13th, gas prices spiked to a now tame-looking price of 200 Gwei and then shot past 400 Gwei. Source: glassnode https://link.medium.com/aJ279KWq7ob

### ISSUE THREAD

**Issue by Mustafakc** [ethereum-optimism/optimistic-specs#364]
What about "*fault proof*"?

Advantages:
1. rolls off the tongue, short
2. sounds similar to "fraud proof"
3. not misleading: doesn't seem to entail something about transactions being invalid, or wrong state roots being necessarily intentional

These may small things, but I think they matter.

Regarding (1), I think "transaction result challenge" is clearest... but also it's a mouthful, people aren't going to bother typing it out. A vote for "transaction result challenge" is a vote for "TRC" because that's what people will end up using.

Regarding (2), *fraud proof* is well established and people are going to continue using it. The real reason we're changing is (a) because fraud implies intent and there isn't always intent behind a wrong state being computed (could be a bug), (b) legal implications of the word "fraud". I think *fault proof* solves both issues while sounding so similar to fraud proof that people will immediately make the connection.

_Originally posted by @norswap in https://github.com/ethereum-optimism/optimistic-specs/discussions/53#discussioncomment-1765216_

**Comment by protolambda** [comment]
This issue looks like a bot copied over a random comment and added more to the title. If there's an actual issue, please ensure there's an action point or question in the post instead of just copy-pasta.

**Comment by Mustafakc** [comment]
Re: [ethereum-optimism/optimistic-specs] What about "*fault proof*"?On 28  March 12th and 13th, gas prices spiked to a now tame-looking price of 200 Gwei and then shot past 400 Gwei. Source: glassnode https://link.medium.com/aJ279KWq7ob (Issue #364)
