### ISSUE TITLE
Handle execution engines errors in the rollup driver

### ISSUE THREAD

**Issue by norswap** [ethereum-optimism/optimistic-specs#47]
The specification of the rollup-node specifies the L2 chain derivation in terms of its interactions with the L2 execution engine.

In the course of normal operations, this should never fail, nor should the execution ever return `"SYNCING"` (since it is being spoon fed all the block inputs by the rollup driver).

How should we allude to error conditions in the spec? And what to do if we hit one?

I'm tempted to just prosaically state the obvious and say that if the execution engine errors out, the rollup-driver is "stuck", and assert that the behaviour is up to implementations to either give up or implement a retry policy (and in any case, to report the issue to the user).

The same questions apply to the case where we are handling a L1 re-org, but there are more subtleties there and I will open a separate issue.

@protolambda Any thoughts?

**Comment by protolambda** [comment]
The API errors are well-specified and I believe not too difficult to implement a robust driver around. I do believe in smaller PRs though. Let's get the rollup-node and exec-engine PRs merged first, then define the API interactions of the driver in more depth.

**Comment by norswap** [comment]
To be clear, I intend this to be in another PR.
Maurelian has request time for him & Ben to review the existing PR before it gets merged.

**Comment by norswap** [comment]
fixed by #60
