### ISSUE TITLE
Specify the L2 execution engine

### ISSUE THREAD

**Issue by norswap** [ethereum-optimism/optimistic-specs#49]
Some stuff that should be in there, from the top of my head:

- Our extensions to the [Engine API specification](https://github.com/ethereum/execution-apis/blob/main/src/engine/specification.md)
- L1 attributes transaction (cf. rollup-node spec, might need input from the deposit feed contract spec)
- Anything else that would work differently than on L1 (??)

Probably separately but should be mentionned:
- predeploys (at least the L1 attributs predeploy)

Probably for later and/or separately:
- https://github.com/ethereum-optimism/optimistic-specs/issues/48
- sync

**Comment by protolambda** [comment]
Opened #52 for execution engine specification.

I believe we should isolate the L1 attributes transaction and predeploy: pre-deploys are just a form of genesis configuration, and the transaction is just another deposit-like transaction. Let's discuss with @maurelian how this deposit/L1 infra should work, and then implement it in a separate PR?
