### ISSUE TITLE
What is the deposit specification?

### ISSUE THREAD

**Issue by karlfloersch** [ethereum-optimism/optimistic-specs#5]
**Is your feature request related to a problem? Please describe.**
Deposit transactions must be included in the rollup. How do we do this?

TODO: Flesh out this issue

**Comment by karlfloersch** [comment]
At a high level we've come to understand that there are 2 major "types" of L1->L2 messages (deposits) that we expect to see:
1. An L1 context update (eg. block hash, block number, base fee, etc)
2. A deposit message coming from an end user.

One big question that we haven't yet answered is exactly how the block processing should work. What currently seems the most promising is updating the baseFee every time a new L1Context has been processed, and then allowing the sequencer to submit as many blocks as they'd like between L1Context updates up to a limit. This would be a EIP1559-like mechanism but over L1Contexts.

**Comment by lightclient** [comment]
Is there a problem with sequencers not including L1 contexts when the base fee drops so they can keep earning a higher data fee?

**Comment by lightclient** [comment]
For the actual data, maybe this?

```rust
struct Context {
    block_hash: Hash,
    number: u64,
    state_root: Root,
    transactions: Hash,
    receipts: Hash,
    base_fee: u256,
    time: u64,
}

struct Message {
    index: u64,
    timestamp: u64,
    sender: Address,
    target: Address
    gas_limit: u64,
    data: Vec<u8>,
}
```

These objects can be i) ABI encoded or ii) hand encoded. I think it would be pretty easy group the values and hand decode them context / msg manager, saving some unnecessary data posted to L1.

**Comment by karlfloersch** [comment]
Noting down some findings after conversations over the weekend debating the need for sequencer priority / deposit transactions in general. Here is a short writeup of the situation:

# Block proposal mechanisms for rollups
1. Free for all
2. Sequencer priority

## Free for all
In a free for all model, anyone can submit a batch to L1 and the batch will be immediately applied to the head of the L2 state. Anyone may propose a next batch, there is no need for a special "deposit" transaction type because there is no risk of censorship by a privileged sequencer. 

#### Benefits
- No deposit transaction type
- Simple to conceptualize

#### Drawbacks
- Creates a race between block proposers which results in:
  - Griefing attacks where an L2 block producer submits a large batch, another L2 block producer sees the batch, submits it themselves with a higher fee, and gets included - winning all the tx fees in the batch. The original block producer's transaction reverts & they need to pay a high fee. The only way this kind of block production can work without this significant griefing attack is if the L1 miner _is_ the block producer (or has a special deal with them to not include reverting txs).
  - An incentive to produce small batches. If you are an L2 block producer, the bigger your batch the more amertized the fixed submission cost is across all of the data that you are submitting. However, if there is no sequencer priorities then the longer the L2 block producer waits to submit, the more likely their txs will be invalidated. This produces a time pressure to submit batches which is bad for users because it means higher fees.

## Sequencer priority
In a sequencer priority model, we introduce a delay to all transactions that are not selected by the current sequencer. The simplest formation of this logic is:

> Block `N` on L2 can be generated by looking at block `n` on L1, and applying all sequencer txs in that block, and then looking at block `n-k` where `k=sequencer_priority` on L1 and applying all deposits in that block as well.

This way the algorithm is still a pure function defined over L1 blocks, but it allows a sequencer a `k` block window where they can submit their transactions and get them included ahead of all other state modifying operations.

#### Benefits
- Sequencer can submit larger batches
- Sequencer cannot get horribly griefed 
- Sequencer can provide low latency "fast confirmations" to users even before transactions are submitted to L1 (because of their submission priority window)

#### Drawbacks
- Slightly more complexity

# Analysis
For multiple reasons it seems that FFA is unfeasible and having a priority window for sequencers is required. However, we do need to come up with a super simple way to express this "deposit" transaction type that has the delay inside of Geth. The reason why it is extra difficult is because there are some fields we want to include in it, like the L1 context & also the L1TxOrigin (the contract address or EOA that initiated the deposit).

**Comment by norswap** [comment]
Why do we need the L1 basefee? Are the L2 fees based on it? Even if that's the case, they could be obtained out-of-band, and there is no way for a users to challenge the sequencer by saying "the sequencer charged me too much given the basefee" (and anyway, under EIP-1559 a node (the sequencer in this case) is still free to censor any transaction that does not tip enough).

**Comment by norswap** [comment]
I understand that, but why does it need to be encoded as L1->L2 message? The sequencer could just query a L1 node (that's what I meant by out-of-bound, as in "not part of the L2 protocol")

**Comment by norswap** [comment]
I'm re-appropriating this issue to track the deposit specification on L1, as what we now call the *deposit feed contract*. This is assigned to @maurelian as per our previous discussion.

@maurelian feel free to close this and reopen another issue if you'd prefer that instead.
