### ISSUE TITLE
Support non-EIP-2718 transactions?

### ISSUE THREAD

**Issue by norswap** [ethereum-optimism/optimistic-specs#50]
In the current rollup node specification, I've only said that we handle [EIP-2718](https://eips.ethereum.org/EIPS/eip-2718) transactions. But Optimistic Ethereum today mostly includes [EIP-155](https://eips.ethereum.org/EIPS/eip-155) transactions.

I don't think there is a way to drop support for those without wiping the chain's history... Which could be an option as long as we figure out the distribution of the "new initial state".

I guess the simple option is to also support EIP-155, but I wanted to check with @protolambda @tynes 

Should we also support pre-EIP-155 transactions?

**Comment by protolambda** [comment]
EIP-155 replay-protected transactions are a subset of the types in EIP-2718: the legacy transaction type of case. And pre-EIP-155 falls into the same legacy type.

With the previous optimism modifications to that transaction type we should check if the backwards compatibility trickery in that EIP still works (a range of transaction type identifiers matches the first byte in the RLP-encoding of the legacy type of transaction).

Given that we would have to put in work to remove it from geth, and break various wallets etc. by removing it, I would prefer to just keep the legacy functionality. And as brought up by @ben-chain, we may want to keep the modified legacy type (currently used in Optimism) so we can have a more seamless transition into spec 1.0 (preserving chain history as well).

**Comment by norswap** [comment]
> EIP-155 replay-protected transactions are a subset of the types in EIP-2718: the legacy transaction type of case. And pre-EIP-155 falls into the same legacy type.

I would dispute this. In reallity, it's unclear because EIP-2718 does not define a "EIP-2718 transaction". It does
- define "typed transaction envelopes"
- say that valid transactions are the old format OR typed transaction envelopes

I (and I suspect many people) think of "typed transaction envelopes" when someone says "EIP-2718 transaction" (as it's a useful distinction from old transactions, otherwise you have "EIP-2718 transactions" == "any transactions").

> With the previous optimism modifications to that transaction type we should check if the backwards compatibility trickery in that EIP still works (a range of transaction type identifiers matches the first byte in the RLP-encoding of the legacy type of transaction).

I wasn't aware of that modification. Yes, we need to check this 👍 

> Given that we would have to put in work to remove it from geth, and break various wallets etc. by removing it, I would prefer to just keep the legacy functionality. And as brought up by @ben-chain, we may want to keep the modified legacy type (currently used in Optimism) so we can have a more seamless transition into spec 1.0 (preserving chain history as well).

Agreed

**Comment by protolambda** [comment]
Correction (thanks @smartcontracts): Optimism currently does not modify the transaction formatting. It does charge additional ETH for L1 usage that is not part of the EIP 155 signed data. See https://github.com/ethereum-optimism/optimism/blob/develop/specs/l2geth/transaction-types.md (outdated, it does not scale gasprice field anymore)

**Comment by tynes** [comment]
For future upgrades, we are considering doing something like EIP-4444 where all of the database indices are downloaded instead of built from transaction execution. This allows for backwards incompatible upgrades, we are calling this method a "squash fork".

**Comment by norswap** [comment]
This is made moot by the fact that deposits are going to be their new transaction types. When we process L2 tx, then we should accept all transactions types, for the sake of EVM equivalence.
