### ISSUE TITLE
How to handle cross-domain contract creation?

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/optimistic-specs#59]
This question [came up](https://github.com/ethereum-optimism/optimistic-specs/pull/54/files#r763604747) while specifying the Deposit Feed Contract. Recording it in an issue to revisit at a future date, at which point it can be polished and converted to a Discussion.

Two options emerged:
> Option A: add an extra field in the event and an extra argument in the function (unless there's a way to detect the nul address from the argument?). We'll alsoneed to check the field in the new transaction type handler and call contract creation logic. And finally, increment nonces on the basis of deposits too.
> Option B: Users have to call a predeployed contract factory instead.

We're going with with Option A for now.

**Comment by norswap** [comment]
Since this is an open question, couldn't we make it a discussion to begin with?

**Comment by maurelian** [comment]
> Since this is an open question, couldn't we make it a discussion to begin with?

sorry I didn't see this at the time!

I'm going to close this for now, as I think we've chosen a good-enough option with the `isCreate` boolean arg, and can revisit if the review of the deposit-only spec release suggests its necessary.
