### ISSUE TITLE
Add build instructions for rollup node implem

### ISSUE THREAD

**Issue by norswap** [ethereum-optimism/optimistic-specs#65]
Quoting from @maurelian at https://github.com/ethereum-optimism/optimistic-specs/pull/58#issuecomment-990163775

> **High level comments:** 
> 
> 1. I need more info in order to be able to run this, for both of the nodes required (`--l1` and `--l2`):
>     1. What repo and git ref should I build it from, or otherwise how should I install it?
>     2. What command and config should I use to run it?
> 
> 2. I think this needs some polish (at least more commenting) to get to the level of readability that @snario has encouraged for a 'reference impl'. However I also recognize the need to **prototype and not die a death by nits in PR review**. To that end I think we should create a `staging` branch, where this could be merged on the basis of "it runs, and the code looks reasonable". Then we could give it more scrutiny to ensure:
> 	1. consistency with the existing spec content
> 	2. Readability, clarity, etc.

@protolambda want to take a first stab at this? rought is fine, e.g. links + an example of the command you use to run it locally with all the flags

**Comment by protolambda** [comment]
The PR description had the basics already

```
go mod download
go run ./opnode run --help
```

Just like any go program, you pull the dependencies and run the main package.

The `--l1` and `--l2` params can specify an RPC address, but although we're opening an RPC client connection, we don't do anything yet, you can ignore them for now.

https://github.com/ethereum-optimism/reference-optimistic-geth/

Is the L2 engine you'll need, `optimism-prototype` branch (only branch on this repo).

After we tackle the remaining work (pull L1 data, deriving L2 blocks, pushing L2), we can describe meaningful local test setups.

**Comment by norswap** [comment]
We clarified this on a call. Currently the various components (L1 node, L2 execution engine, rollup node) are not interconnected, so this is not very useful yet, but will come in time.

**Comment by protolambda** [comment]
Lost track of this issue, but as shared in chats/calls: https://github.com/protolambda/rollup-node-experiments has all the instructions you need to run the staging branch end-to-end.

Will add usage instructions / `opnode/README.md` to tasks tracker for `staging -> main` work.

**Comment by maurelian** [comment]
Can we close this?

**Comment by norswap** [comment]
I think we need to strive to move something like what we have in https://github.com/protolambda/rollup-node-experiments to this repo. Lots of value of having up-to-date instructions on how to build & run the whole system.

Could be moved to the TLC milestone however.
