### ISSUE TITLE
Ref Impl: Engine API: Bindings

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/optimistic-specs#67]
Transferred from ENG-1742

**Comment by protolambda** [comment]
API changes (backwards compatible) in geth can be found here: https://github.com/ethereum-optimism/reference-optimistic-geth/blob/optimism-prototype/eth/catalyst/api.go

API bindings can be found here: https://github.com/ethereum-optimism/optimistic-specs/blob/staging/opnode/l2/api.go
