### ISSUE TITLE
Ref Impl: Block derivation code

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/optimistic-specs#69]
Transferred from ENG-1740

**Comment by norswap** [comment]
Not that it couldn't change anymore, but the code is there (https://github.com/ethereum-optimism/optimistic-specs/pull/83), marking this done.

**Comment by maurelian** [comment]
Not yet in main branch

**Comment by norswap** [comment]
With https://github.com/ethereum-optimism/optimistic-specs/pull/129 merged, we can close this.
