### ISSUE TITLE
Ref Impl: Engine: Support for Deposit Tx type

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/optimistic-specs#70]
Transferred from ENG-1743

**Comment by protolambda** [comment]
See https://github.com/ethereum-optimism/reference-optimistic-geth/commit/9187d4ade1523ab8f0e7789ce6c3105c95f0d8b8

Rebased today onto the latest `kintsugi-merge` branch of Marius. The type is supported, but the driver will still need to derive it from L1 info and encode it to binary form like the other transactions. That is part of #69 

Closing this
