### ISSUE TITLE
Create a Development Environment for Integration Testing

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/optimistic-specs#79]
This is a longer term consideration. 

Roughly, this should allow us to easily initiate: 
- An L1 node
- A Rollup Driver
- An Execution engine (L2 Node)

**Comment by maurelian** [comment]
Having worked through the example in https://github.com/protolambda/rollup-node-experiments, I can now see the need to do this sooner than later.

**Comment by protolambda** [comment]
Moving this to the Tender Loving Care milestone. With the rollup-node-experiments repo and the e2e integration tests in Go this issue may also be closed, but we will continue to improve it.

**Comment by maurelian** [comment]
I think we can close, and create a new issue when we have more concrete ideas.
