### ISSUE TITLE
Specify ETH & ETH deposit handling

### ISSUE THREAD

**Issue by norswap** [ethereum-optimism/optimistic-specs#85]
cf. this comment: https://github.com/ethereum-optimism/optimistic-specs/pull/66
and historical context: https://github.com/ethereum-optimism/optimistic-specs/discussions/84

On the current EVM, the storage for balances are always 0 BUT this doesn't change anything for users: things like the `BALANCE` opcode are hardwire to a ERC20 contract whose transfer and approval functions all revert.

One downside of that difference is that a Merkle proof scheme for proving user balances on L1 would need to be modified to work on L2.

On the other hand, using native ETH has design implications: we can't use the bridge pattern anymore (since you can't "mint" the native currency in a contract) and would need to add a new deposit transaction type, which would be interpreted specially by the execution engine and cause ETH to be minted.

Questions:
- Do we want to track ETH in the proper storage slots in Optimism 1.0?
- If so, how do we design the mechanism for minting native ETH? Is the custom transaction type the only option?

Random remarks:
- We can't expose ETH as both an ERC20 and the normal balances, because that would violate programmer's assumptions (you don't expect that transaction with an ERC20 would change the ETH balance underneath you).
- We don't need to support sending ETH as part of a deposit: i.e. calling a contract X + minting ETH in the same deposit. Instead, a contract always has the option to perform two deposits instead: one that calls contract X and one that mints ETH (via the standard ETH bridge).

**Comment by maurelian** [comment]
Related discussion on #68

**Comment by norswap** [comment]
One major issue with the current design (deposits have a "value" that is ETH locked in the deposit contract and subsequently minted on L2) is that this does not allow deposit to spend ETH from their associated L1 contracts.

We thought of two solutions:
1. Do not lock ETH in the deposit contract, any sent value is L2 ETH. The behaviour of sending (or calling a contract with) L1 ETH can be reproduced by first depositing the ETH, then sending it. To deposit the ETH, a message would be sent to a special pre-compiled contract that mints L2 ETH. Only a L1 ETH bridge contract would be allowed to call this conctract to mint.
2. Have two fields on deposit transaction, one for the L1 ETH value, one for the L2 ETH value. In another PR, proto has named these `mint` and `value` respectively, which I kinda like (althought it should be clarified that they are both like the normal value field: they are both sent with the transaction).

I was slightly leaning towards solution (1) (mostly to avoid us having to explicitly encode the bridge pattern in the spec and stay at the level of lower primitives) but maurelian was in favour of (2), on the grounds that ETH is special and avoiding the complexity of an ETH-minting precompile.

We decided to go with solution (2), and I'm repurposing this issue to track its implementation.

Another concern is enabling withdrawal, but that will be tackled after the deposits-only milestone.

**Comment by norswap** [comment]
This seems completed by #95 to me, closing.
